# -*- coding: utf-8 -*-
# Spécification de la vidéo consolidée « le notaire Félix BALLEY » (à l'attention d'un avocat)
N='le notaire Félix BALLEY'
def card(h,col='L'): return (col,'card',h)
def big(h,col='L'): return (col,'big',h)
def pic(f,cap=None,col='R'): return (col,'pic',(f,cap))
def q(h,col='L'): return (col,'q',h)

SCENES=[]
def scene(tag,*cues,style=''): SCENES.append(dict(tag=tag,cues=list(cues),style=style))
def cue(sub,*items,voice=None): return dict(sub=sub,items=list(items),voice=voice)

scene("Introduction",
 cue("Cette vidéo s'adresse à un avocat. Elle démontre, pièce par pièce, comment le notaire Félix BALLEY a manqué à ses obligations légales et déontologiques.",
     big("Le notaire Félix BALLEY<br><span class='gold'>face à ses obligations légales et déontologiques</span>")),
 cue("Chaque affirmation renvoie à une pièce du dossier. Les textes sont cités avec leur source. Ce qui reste à vérifier est signalé comme tel.",
     card("<b class='gold'>Méthode</b><br>Une affirmation, une pièce, un texte.<br>Ce qui n'est pas prouvé est signalé.")),
 cue("Cinq manquements seront examinés : l'exactitude de la date, la qualité de mandataire, l'inscription au répertoire, la transparence, et les déclarations devant la Brigade criminelle.",
     card("<b>1</b> · Exactitude de la date<br><b>2</b> · Qualité de mandataire<br><b>3</b> · Inscription au répertoire<br><b>4</b> · Transparence<br><b>5</b> · Déclarations devant la Brigade criminelle")))

scene("Le cadre : le statut du notariat (loi n° 2002-015 du 30 décembre 2002)",
 cue("Le notaire Félix BALLEY est officier public et ministériel. L'article 1er du statut du notariat le charge d'assurer la date des actes et d'en conserver le dépôt.",
     card("<b class='gold'>Art. 1er</b> : officier public et ministériel, chargé « d'assurer la date de ces actes et contrats, d'en conserver le dépôt »")),
 cue("L'article 33 impose, dès la nomination, le serment de remplir ses fonctions avec exactitude et probité. Le notaire Félix BALLEY, en exercice, y est tenu.",
     pic('serment.jpg','Statut du notariat, article 33'),card("<b class='gold'>Art. 33</b> : « Je jure de remplir mes fonctions avec exactitude et probité »")),
 cue("L'article 47 le déclare disciplinairement et pénalement responsable des fautes commises dans l'accomplissement de son ministère.",
     pic('art47.jpg','Statut du notariat, article 47'),card("<b class='gold'>Art. 47</b> : responsabilité disciplinaire et pénale personnelle"))) 

scene("Les faits et les pièces",
 cue("Le 3 décembre 2010, Jean Florentin Féliho décède à Cotonou. La déclaration de décès du CNHU, le jugement de 2014 et le procès-verbal de lecture du testament le confirment.",
     card("<b class='gold'>3 déc. 2010</b> — décès de Jean Florentin FÉLIHO"),pic('deces.jpg','Déclaration de décès, CNHU-HKM')),
 cue("Le 30 août 2012, Maître Lazare Crinot est nommé administrateur de la succession, ce que publie le communiqué du 3 avril 2013 dans le journal La Nation.",
     card("<b class='gold'>30 août 2012</b> — arrêt n° 28/12 : Maître Lazare CRINOT administrateur"),pic('communique-crinot.jpg','Communiqué, La Nation, 3 avril 2013')),
 cue("Le 31 octobre 2014, le Tribunal de Cotonou juge la succession : décès le 3 décembre 2010. Le notaire Félix BALLEY n'y figure pas.",
     card("<b class='gold'>31 oct. 2014</b> — jugement n° 114/14 : décès le 3 décembre 2010"),pic('jug-deces.jpg','Jugement n° 114/14, page 6')),
 cue("Le 10 août 2016, la déclaration de mutation par décès est enregistrée dans le répertoire de l'Étude du notaire Félix BALLEY, sous le numéro 1428. Le 20 octobre 2016, le certificat est délivré.",
     card("<b class='gold'>10 août 2016</b> — DMD n° 1428 au répertoire de l'Étude<br><b class='gold'>20 oct. 2016</b> — certificat d'acquit de droit"),pic('dgi-1428.jpg','Courrier DGI du 6 janvier 2025, page 2')),
 cue("Le 4 août 2023, Gilles Féliho fait signifier une sommation de compulsion. Le 7 septembre 2023, le notaire Félix BALLEY répond. Le 6 janvier 2025, la DGI formule ses observations.",
     card("<b class='gold'>4 août 2023</b> — sommation (compulsion du répertoire)<br><b class='gold'>7 sept. 2023</b> — réponse du notaire Félix BALLEY<br><b class='gold'>6 janv. 2025</b> — observations de la DGI")),
 cue("Le 19 mars 2025, le notaire Félix BALLEY est entendu par la Brigade criminelle. Le 28 mai 2025, Gilles Féliho met en demeure l'administration de produire la preuve du mandat.",
     card("<b class='gold'>19 mars 2025</b> — audition du notaire Félix BALLEY (BAC)<br><b class='gold'>28 mai 2025</b> — mise en demeure à l'administration")))

scene("Identifier l'acte du notaire Félix BALLEY",
 cue("Il faut d'abord identifier l'acte reproché. Le certificat d'acquit de droit n'est pas délivré par le notaire Félix BALLEY, mais par l'Inspecteur de l'enregistrement.",
     card("Le certificat est délivré par l'Inspecteur de l'enregistrement<br><span class='mute'>(Rodrigue S. DANSOU, 20 octobre 2016)</span>"),pic('cert-deces-mandat.jpg','Certificat d\'acquit de droit, 20 octobre 2016')),
 cue("Mais, selon la Direction générale des impôts, il a été sollicité par l'Étude du notaire Félix BALLEY et il reflète les informations portées sur la déclaration de mutation par décès.",
     card("Selon la DGI : « sollicité par l'Étude de Maître Félix A. BALLEY » ; le certificat « reflète les informations portées sur la DMD »"),pic('dgi-sollicite.jpg','Courrier DGI du 6 janvier 2025, page 2')),
 cue("Cette déclaration est enregistrée dans le répertoire de l'Étude le 10 août 2016, sous le numéro 1428, à la page 128. Le répertoire est clos le 7 octobre 2016, sous le numéro 1492.",
     card("DMD : répertoire de l'Étude, <b>n° 1428, page 128</b>, 10 août 2016<br>Répertoire clos le 7 octobre 2016, n° 1492, page 132")),
 cue("La déclaration elle-même et l'extrait du répertoire ne figurent pas au dossier. La date qu'elle porte est déduite du certificat, que la DGI dit conforme à elle. Ces pièces sont à obtenir.",
     card("<b class='red'>Pièces absentes du dossier</b><br>La DMD · l'extrait du répertoire n° 1428",'L')))

scene("Premier manquement : l'exactitude de la date",
 cue("L'article 438 du Code général des impôts impose de déclarer la succession dans les six mois du décès, lorsque celui-ci survient au Bénin.",
     card("<b class='gold'>CGI, art. 438</b> : délai de <b>six mois</b> à compter du décès, si le décès est arrivé au Bénin")),
 cue("Le décès a eu lieu le 3 décembre 2010. Le délai expirait donc le 3 juin 2011.",
     card("Décès : <b class='green'>3 décembre 2010</b><br>Limite légale : <b>3 juin 2011</b>"),pic('jug-deces.jpg','Jugement n° 114/14, page 6')),
 cue("La déclaration est enregistrée le 10 août 2016 : cinq ans et deux mois de retard avec la vraie date de décès.",
     card("<b class='red'>+ 5 ans et 2 mois</b> de retard<br>(déclaration du 10 août 2016)")),
 cue("Le certificat indique un décès le dix juin deux mille seize. Avec cette date, la déclaration du 10 août 2016 se situe à deux mois du décès : elle paraît dans le délai.",
     card("Certificat : décès « <b class='red'>le dix juin deux mil seize</b> »<br>Écart : <b>2 mois</b>, « dans le délai »"),pic('cert-deces.jpg','Certificat d\'acquit de droit')),
 cue("Cette date est impossible : un jugement du 31 octobre 2014 a déjà statué sur la succession. Elle fait disparaître la violation de l'article 438.",
     card("Un décès en juin 2016 est <b class='red'>impossible</b> : le jugement du 31 octobre 2014 statue déjà sur la succession")),
 cue("Le manquement porte sur l'exactitude, que l'article 1er et le serment de l'article 33 imposent au notaire Félix BALLEY, chargé d'assurer la date des actes.",
     card("<b class='gold'>Art. 1er + art. 33</b> : « assurer la date » · exactitude et probité")))

scene("Deuxième manquement : la qualité de mandataire",
 cue("Le certificat dit que la mutation a été souscrite par le notaire Félix BALLEY, agissant en qualité de mandataire et au nom des héritiers, dont Gilles Féliho.",
     pic('cert-deces-mandat.jpg','Certificat d\'acquit de droit'),card("« agissant en qualité de <b class='red'>mandataire</b> et au nom des héritiers suivants » — dont Gilles Sixte FÉLIHO")),
 cue("Le mandat est défini par l'article 1984 du Code civil : un acte par lequel une personne donne à une autre le pouvoir de faire quelque chose pour elle et en son nom.",
     card("<b class='gold'>Code civil, art. 1984</b> : « un acte par lequel une personne donne à une autre le pouvoir de faire quelque chose pour le mandant et en son nom »")),
 cue("L'article 61 du statut impose d'annexer la procuration à l'acte, ou de la déposer au rang des minutes avec mention dans l'acte. Il suffirait de la produire.",
     pic('art61.jpg','Statut du notariat, article 61'),card("<b class='gold'>Statut, art. 61</b> : procuration annexée à l'acte ou déposée au rang des minutes")),
 cue("Aucun mandat n'a été produit. La DGI relève que Gilles Féliho allègue n'avoir jamais été associé à cette déclaration.",
     card("<b class='red'>Aucun mandat produit</b><br>Gilles FÉLIHO « allègue n'y avoir jamais été associé » (DGI)")),
 cue("Le 28 mai 2025, Gilles Féliho met en demeure l'administration de produire la preuve écrite du mandat. Elle n'a pas répondu à ce jour.",
     pic('mise-preuve.jpg','Mise en demeure du 28 mai 2025'),card("Mise en demeure du 28 mai 2025 : « la preuve écrite du mandat »<br><b class='red'>Sans réponse</b>")),
 cue("Le 7 septembre 2023, le notaire Félix BALLEY écrit que Gilles Féliho n'est pas partie aux actes dont il demande la délivrance.",
     pic('balley-lettre.jpg','Lettre du notaire Félix BALLEY, 7 septembre 2023'),card("« la délivrance d'actes auxquels il n'est pas partie »")),
 cue("Le notaire Félix BALLEY ne peut pas être à la fois le mandataire de Gilles Féliho et l'officier public pour qui Gilles Féliho n'est pas partie à ses actes.",
     big("<span class='red'>Mandataire</span> de Gilles FÉLIHO<br>ou <span class='red'>tiers</span> à ses actes ?")),
 cue("Devant la Brigade criminelle, le notaire Félix BALLEY déclare que le dossier lui a été transmis par l'ensemble de la succession, sauf Gilles Féliho.",
     pic('pv-dossier.jpg','PV d\'audition du 19 mars 2025, page 2/5'),card("PV : « Le dossier m'a été transmis par l'ensemble de la succession <b class='red'>sauf lui</b> »")),
 cue("Trois justifications successives et incompatibles : mandataire dans le certificat, tiers non partie dans la lettre de 2023, nom contenu dans le testament devant la Brigade criminelle.",
     card("<b>1.</b> Certificat : mandataire<br><b>2.</b> Lettre du 7 sept. 2023 : tiers non partie<br><b>3.</b> PV du 19 mars 2025 : « son nom était contenu dans le testament »")))

scene("L'absence de titre du notaire Félix BALLEY dans la succession",
 cue("Le notaire Félix BALLEY déclare avoir été saisi d'une exécution partielle du testament. Rien au dossier ne lui donne ce titre.",
     pic('pv-execution.jpg','PV d\'audition, page 5/5'),card("PV : « dont j'ai été saisi d'une <b class='red'>exécution partielle</b> »")),
 cue("Le testament avait été déposé chez Maître Irène Adjagba Ichola, selon le procès-verbal de lecture de 2012 et le courriel de son étude du 21 novembre 2013. Le notaire Félix BALLEY n'y figure pas.",
     card("<b class='gold'>Dépositaire</b> : Maître Irène ADJAGBA ICHOLA<br>PV de lecture 2012 · courriel du 21/11/2013<br><span class='red'>Le notaire Félix BALLEY n'y figure pas</span>")),
 cue("Maître Lazare Crinot a été nommé administrateur par l'arrêt numéro 28/12 du 30 août 2012. Le communiqué du 3 avril 2013 ne mentionne pas le notaire Félix BALLEY.",
     card("<b class='gold'>Administrateur</b> : Maître Lazare CRINOT (arrêt n° 28/12)<br><span class='red'>Le notaire Félix BALLEY n'y figure pas</span>"),pic('communique-crinot.jpg','Communiqué, La Nation, 3 avril 2013')),
 cue("Honorine Bah est désignée liquidatrice par l'ordonnance numéro 842/2013. Cette désignation s'est faite à l'insu de Gilles Féliho : l'ordonnance ne lui a jamais été signifiée et il n'en a jamais eu connaissance. Aucune signification n'est produite, et la preuve en incombe à celui qui se prévaut de l'ordonnance. Le jugement de 2014 ne mentionne pas le notaire Félix BALLEY.",
     card("<b class='gold'>Liquidatrice</b> : Honorine BAH (ordonnance n° 842/2013)<br><span class='red'>Jamais signifiée à Gilles FÉLIHO · jamais portée à sa connaissance</span><br><span class='mute'>Aucune signification produite : la preuve incombe à celui qui se prévaut de l'ordonnance</span><br><span class='red'>Le notaire Félix BALLEY n'y figure pas</span>")),
 cue("Le Code des personnes et de la famille ne connaît qu'un exécuteur nommé par le testateur : article 940. Rien n'établit cette nomination pour le notaire Félix BALLEY.",
     card("<b class='gold'>CPF, art. 940</b> : le testateur peut nommer un exécuteur testamentaire<br><span class='red'>Aucune désignation produite</span>")),
 cue("Même un exécuteur a une saisine limitée aux meubles et à un an et un jour après le décès : article 941. Il a les pouvoirs d'un mandataire : article 943.",
     card("<b class='gold'>CPF, art. 941</b> : saisine des <b>meubles</b>, un an et un jour<br><b class='gold'>CPF, art. 943</b> : pouvoirs d'un mandataire")),
 cue("Il doit faire l'inventaire en présence de l'héritier présomptif, ou lui dûment appelé : article 944. Aucun inventaire ni appel de Gilles Féliho n'est produit.",
     card("<b class='gold'>CPF, art. 944</b> : inventaire en présence de l'héritier présomptif ou lui dûment appelé<br><span class='red'>Aucun inventaire produit</span>")),
 cue("La déclaration du notaire Félix BALLEY porte sur des immeubles et date de 2016, près de six ans après le décès. Ce n'est pas l'exercice d'une saisine d'exécuteur.",
     big("Des <span class='red'>immeubles</span>, en <span class='red'>2016</span> :<br>pas une saisine d'exécuteur")))

scene("Troisième manquement : l'inscription au répertoire",
 cue("L'article 76 impose de tenir un répertoire de tous les actes reçus, et l'article 77 de le soumettre chaque trimestre à l'inspecteur de l'enregistrement. Le notaire Félix BALLEY y est tenu.",
     pic('art76.jpg','Statut du notariat, article 76'),card("<b class='gold'>Art. 76</b> : répertoire de tous les actes reçus<br><b class='gold'>Art. 77</b> : présentation trimestrielle à l'inspecteur")),
 cue("La déclaration de mutation par décès est inscrite au répertoire du notaire Félix BALLEY le 10 août 2016, sous le numéro 1428, à la page 128.",
     pic('dgi-1428.jpg','Courrier DGI du 6 janvier 2025'),card("DMD inscrite : <b>n° 1428, page 128</b>, 10 août 2016")),
 cue("Cette inscription intervient près de deux ans après le jugement du 31 octobre 2014, et plus de trois ans après le communiqué publié dans La Nation le 3 avril 2013.",
     card("<b class='red'>Près de 2 ans</b> après le jugement (31/10/2014)<br><b class='red'>Plus de 3 ans</b> après le communiqué (03/04/2013)")),
 cue("Ces pièces publiques existaient avant l'inscription. Elles rendent la date du dix juin deux mille seize impossible à soutenir sans les ignorer.",
     big("La date du 10 juin 2016<br><span class='red'>impossible à soutenir</span>")),
 cue("La DGI tient ensuite le certificat pour authentique, et ne dit rien du prétendu mandat. Le certificat a donc été utilisé.",
     card("DGI : « le Certificat d'Acquit de Droit est <b>authentique</b> »<br><span class='red'>Rien sur le mandat</span>")))

scene("Quatrième manquement : la transparence",
 cue("L'article 82 du statut permet de délivrer expédition et connaissance des actes aux personnes intéressées en nom direct, aux héritiers ou aux ayants droit, sans ordonnance.",
     pic('art82.jpg','Statut du notariat, article 82'),card("<b class='gold'>Art. 82</b> : ordonnance requise pour les personnes <b>autres</b> que les intéressés, héritiers ou ayants droit")),
 cue("Gilles Féliho est héritier. Le 7 septembre 2023, le notaire Félix BALLEY lui oppose pourtant la confidentialité et l'absence d'ordonnance judiciaire.",
     card("Gilles FÉLIHO est <b class='green'>héritier</b><br>Le notaire Félix BALLEY invoque « la confidentialité » et l'absence « d'ordonnance judiciaire »"),pic('balley-lettre.jpg','Lettre du 7 septembre 2023')),
 cue("Le notaire Félix BALLEY juge l'exposé de griefs de la sommation du 4 août 2023 ne nécessitant aucune réponse.",
     card("« un exposé de griefs ne nécessitant aucune réponse »")),
 cue("Devant la Brigade criminelle, le notaire Félix BALLEY affirme avoir ouvert grandement son répertoire à la commission de contrôle, qui n'aurait trouvé aucun document du genre.",
     pic('pv-repertoire.jpg','PV d\'audition, page 5/5'),card("PV : « J'ai ouvert grandement mes portes et mon répertoire à la commission de contrôle »")),
 cue("En 2023, le notaire Félix BALLEY refusait donc l'accès à son répertoire à un héritier. En 2025, il dit l'avoir ouvert à l'administration.",
     card("2023 : accès refusé à un héritier<br>2025 : répertoire « ouvert » à l'administration")),
 cue("L'administration, elle, n'a pas répondu aux cinq questions de la sommation interpellative ni à la mise en demeure du 28 mai 2025.",
     card("<b class='red'>Sans réponse de l'administration</b> : les 5 questions de la sommation interpellative · la mise en demeure du 28 mai 2025")))

scene("Cinquième manquement : les déclarations devant la Brigade criminelle",
 cue("Le procès-verbal numéro 2 du 19 mars 2025 est une audition de témoin dans une enquête pour usage de faux. Sont nommés comme personnes soupçonnées Victorin Fade, Félix Balley et Albin Féliho.",
     card("PV n° 2 · 19 mars 2025 · infraction : <b>usage de faux</b><br>Soupçonnés : Victorin FADE, Félix BALLEY, Albin FELIHO<br>Victime : Sixte Giles FELIHO"),pic('pv-dossier.jpg','Audition du 19 mars 2025, page 2/5')),
 cue("La copie remise ne comporte que les pages 1, 2/5 et 5/5. Les pages 3/5 et 4/5 sont absentes et sont à demander.",
     card("<b class='red'>Pages 3/5 et 4/5 absentes</b> de la copie remise<br>Analyse limitée aux pages 1, 2/5 et 5/5")),
 cue("Le notaire Félix BALLEY déclare que le testament a été confirmé par le jugement du 31 octobre 2014. Or le jugement constate l'exécution volontaire par Gilles Féliho et déclare sa demande en nullité irrecevable.",
     pic('pv-confirme.jpg','PV d\'audition, page 2/5'),card("Jugement : « constate » l'exécution, déclare la demande en nullité <b>irrecevable</b> — il ne mentionne jamais le notaire Félix BALLEY")),
 cue("Le jugement constate une exécution volontaire par Gilles Féliho. Or il ne cite ni acte de vente, ni rédacteur de l'acte, ni acquéreur, ni date, ni prix. Ce constat repose sur la seule affirmation des autres héritiers.",
     card("Jugement n° 114/14, page 8 : « Constate que Gilles Sixte FELIHO a exécuté les dispositions testamentaires de manière volontaire »<br><span class='red'>Aucun acte de vente · aucun rédacteur de l'acte · aucun acquéreur · aucune date · aucun prix</span>")),
 cue("Le bien visé est la parcelle B du lot 488 de Gbégamey. Par procès-verbal des 19 et 21 décembre 2017, l'huissier interroge la Mairie de Cotonou et l'Institut Géographique National : ni l'une ni l'autre n'en a trace.",
     card("Mairie de Cotonou, 23 février 2018 : superficie <b>néant</b><br>IGN : <b>aucun document</b> afférent à la parcelle B du lot 488<br><span class='mute'>Procès-verbal de compulsion, 19 et 21 décembre 2017</span>")),
 cue("La seule pièce du dossier sur un terrain de Gilles Féliho à Gbégamey date de 2007, avant le décès. Elle vise la parcelle B du lot 923. Aucun acte de disposition après le décès n'est établi : l'exécution volontaire ne l'est donc pas.",
     card("Lettre du 19 septembre 2007 : parcelle B du <b>lot 923</b>, dont Gilles FÉLIHO est propriétaire<br><span class='red'>Antérieure au décès du 3 décembre 2010 · aucun acte post-mortem établi</span>")),
 cue("Le notaire Félix BALLEY déclare que les montants utilisés relevaient des estimations faites par leur feu père. Aucune pièce ne l'établit. Le manuscrit du 12 juillet 2007 ne contient pas ces montants.",
     pic('pv-estimations.jpg','PV d\'audition, page 5/5'),card("« les montants utilisés relevaient des estimations faites par leur feu père » — <span class='red'>sans pièce-source</span>")),
 cue("Le notaire Félix BALLEY écarte la critique des valeurs en disant que le système fiscal béninois est déclaratif. Cela ne répond ni à la date de décès ni à l'article 438.",
     card("« le système fiscal béninois est déclaratif »<br><span class='red'>Ne répond pas à la date de décès</span>")),
 cue("Le notaire Félix BALLEY affirme n'avoir jamais soustrait le nom de Gilles Féliho sur un document pour en faire usage. Or le certificat est un document établi au nom des héritiers, dont Gilles Féliho.",
     pic('pv-execution.jpg','PV d\'audition, page 5/5'),card("« je n'ai jamais soustrait son nom à part sur un document pour en faire usage » — le <b>certificat</b> porte ce nom")),
 cue("La commission de contrôle n'aurait trouvé aucun document du genre. Or la DGI relève que la déclaration de mutation par décès est enregistrée sous le numéro 1428 dans le répertoire de l'Étude.",
     card("« aucun document du genre » ≠ DMD retrouvée, <b>n° 1428</b> (DGI)")),
 cue("Le notaire Félix BALLEY dit qu'un procès-verbal de vérification a été rédigé et qu'il en apportera copie. La pièce versée est un courrier d'observations de la DGI, pas ce procès-verbal.",
     card("« un procès-verbal a été rédigé et je vous porterai copie »<br><span class='red'>Non produit</span>")),
 cue("Le notaire Félix BALLEY invoque une interpellation verbale de l'inspecteur général des finances en 2017. Aucune pièce ne l'établit.",
     card("2017 : interpellation « verbale »<br><span class='red'>Aucune pièce produite</span>")),
 cue("Devant l'Autorité de protection des données personnelles, le 19 juin 2024, le notaire Félix BALLEY présente une autre justification. Son action ferait suite à une décision de justice devenue exécutoire, qui l'obligerait à consulter les dossiers.",
     pic('apdp-decision.jpg','Procès-verbal de séance de l\'APDP, 19 juin 2024, page 3/3'),card("19 juin 2024 : « son action fait suite à une <b class='gold'>décision de justice devenue exécutoire</b> » qui « l'oblige à consulter les dossiers »")),
 cue("Quelle décision ? Le jugement de 2014 ne mentionne pas le notaire Félix BALLEY. Il constate et déclare irrecevable. Il ne lui ordonne rien. Et devant la Brigade criminelle, le notaire Félix BALLEY invoquait une autre base : une exécution partielle du testament.",
     card("Jugement n° 114/14 : <b>aucun ordre</b> adressé à un notaire · le notaire Félix BALLEY n'y figure pas<br><span class='red'>APDP, 2024 : une décision de justice</span><br><span class='red'>Brigade criminelle, 2025 : une exécution partielle</span><br><span class='red'>Certificat : un mandat</span>")),
 cue("Il déclare n'avoir collecté aucune donnée, tout étant contenu dans la décision. Or le jugement retient trente-neuf immeubles pour cinq cent soixante-sept millions neuf cent quatre-vingt-dix mille francs, et un décès au trois décembre deux mille dix. Le certificat porte sept immeubles, cent trente-huit millions trois cent mille francs, et un décès au dix juin deux mille seize.",
     card("« aucune donnée collectée, tout étant contenu dans la décision »<br>Jugement : 39 immeubles · 567 990 000 FCFA · décès le <b>3 décembre 2010</b><br>Certificat : 7 immeubles · 138 300 000 FCFA · décès le <b class='red'>10 juin 2016</b><br><span class='red'>Ces données ne sont pas dans la décision</span>")),
 cue("Son avocat soutient que les faits sont antérieurs au code du numérique, et s'excuse au nom de son client de l'ignorance de l'obligation de mise en conformité. Ce n'est pas compatible avec l'affirmation qu'aucune donnée n'a été collectée.",
     pic('apdp-avlessi.jpg','Procès-verbal de séance de l\'APDP, 19 juin 2024, page 3/3'),card("Son avocat : faits « antérieurs » au code · excuses pour « l'ignorance de l'obligation légale de mise en conformité »<br><span class='red'>≠ « aucune donnée collectée »</span>")),
 cue("Cette procédure concerne la protection des données personnelles. Elle ne tranche pas la question du mandat, qui dépend du seul consentement de Gilles Féliho. Elle sert ici à relever les contradictions du notaire Félix BALLEY.",
     card("Protection des données ≠ mandat<br><span class='mute'>Le mandat relève du seul consentement de Gilles FÉLIHO</span>")),
 cue("Une remarque sur le procès-verbal lui-même : il porte l'an deux mille vingt-quatre, alors que l'en-tête indique le 19 mars 2025, un mercredi. C'est une erreur de rédaction de l'officier de police judiciaire.",
     card("Corps du PV : « L'an deux mil vingt-quatre et le mercredi dix-neuf mars »<br>En-tête : <b>19 mars 2025</b> (un mercredi)<br><span class='mute'>Erreur de rédaction de l'OPJ, non imputable au notaire Félix BALLEY</span>")))

scene("Le constat d'huissier du 29 juillet 2022 : l'« exécution partielle » à l'épreuve des faits",
 cue("Le notaire Félix BALLEY affirme avoir été saisi d'une exécution partielle du testament. Un procès-verbal de constat du 29 juillet 2022 permet de confronter cette affirmation à la réalité des lieux.",
     card("<b class='gold'>29 juillet 2022</b> — procès-verbal de constat avec interpellation<br>Maître Marc O. A. Orekan, huissier de justice, à Cotonou"),pic('pvc-requete.jpg','Constat d\'huissier du 29 juillet 2022, page 1')),
 cue("À la requête de Gilles Féliho, l'huissier se rend à l'immeuble dit Immeuble évènementiel, à Cotonou, pour constater l'occupation des appartements que Gilles Féliho dit avoir hérités de son père.",
     card("Objet : constater l'occupation des appartements « qu'il a hérité de son feu père »<br><span class='mute'>Désignation donnée par le requérant</span>")),
 cue("Au deuxième étage, une plaque indique que l'appartement est occupé par la société Vissim. Un membre de son personnel, Monsieur Alain Alona, déclare que la société Vissim a pris les lieux à bail auprès de la société évènementiel.",
     pic('pvc-bail.jpg','Constat d\'huissier, page 2'),card("Occupant : société <b>VISSIM</b><br>Déclaration d'un employé : bail « auprès de la société évènementiel »")),
 cue("L'huissier se rend au siège de la société évènementiel, au troisième étage. Le Directeur Général et son adjoint sont absents. Aucune interpellation n'a pu être faite.",
     pic('pvc-absents.jpg','Constat d\'huissier, page 2'),card("Siège de la société évènementiel : <b>3e étage</b><br>Directeur Général et adjoint absents — <span class='red'>aucune interpellation</span>")),
 cue("Ce que le constat établit : un appartement du bien est occupé par la société Vissim, qui déclare le tenir à bail de la société évènementiel. Ce que dit Gilles Féliho : cette société appartient à Albin Féliho.",
     card("<b class='gold'>Établi</b> : occupation par VISSIM ; bail déclaré, consenti par la société évènementiel<br><b class='gold'>Selon Gilles Féliho</b> : la société évènementiel appartient à Albin FELIHO")),
 cue("Ce que le constat n'établit pas : le bail lui-même n'est pas produit, la propriété de la société par Albin Féliho ne figure pas au procès-verbal, et le procès-verbal ne mentionne pas le notaire Félix BALLEY.",
     card("<b class='red'>Non établi par le constat</b><br>Le bail n'est pas produit<br>Propriétaire de la société évènementiel : absent du procès-verbal<br>Le notaire Félix BALLEY n'y est pas mentionné")),
 cue("La question posée est donc celle-ci. Comment un bien légué à Gilles Féliho est-il loué, à son insu, par une société que Gilles Féliho dit appartenir à Albin Féliho ? Et de quelle exécution partielle le notaire Félix BALLEY a-t-il été saisi ?",
     big("Un bien légué à Gilles FÉLIHO,<br><span class='gold'>loué à son insu</span> par la société évènementiel.<br><span class='red'>De quelle « exécution partielle » le notaire Félix BALLEY a-t-il été saisi ?</span>")),
 cue("Pour l'établir, il faut le bail, le titre foncier de l'immeuble, l'extrait du registre du commerce de la société évènementiel, et l'acte dont le notaire Félix BALLEY dit avoir été saisi.",
     card("<b class='red'>À obtenir</b> : bail · titre foncier · registre du commerce de la société évènementiel · acte de « l'exécution partielle »")))

scene("La qualification : textes à vérifier sur le texte officiel",
 cue("Les articles pénaux qui suivent sont à vérifier sur le texte officiel de l'ancien code pénal, dit code Bouvenet, applicable en 2016.",
     card("<b class='red'>À vérifier</b><br>Textes à contrôler sur le texte officiel de l'ancien code pénal (code Bouvenet), applicable en 2016")),
 cue("L'article 145 vise l'officier public qui commet un faux dans une écriture publique, y compris par des écritures faites ou intercalées dans des registres.",
     card("<b class='gold'>Art. 145</b> : faux de l'officier public dans une écriture publique, y compris écritures faites ou intercalées dans des registres")),
 cue("L'article 146 vise l'officier public qui, en rédigeant des actes de son ministère, constate comme vrais des faits faux, ou comme avérés des faits qui ne l'étaient pas.",
     card("<b class='gold'>Art. 146</b> : « en constatant comme vrais des faits faux, ou comme avérés des faits qui ne l'étaient pas »")),
 cue("L'article 148 vise l'usage sciemment fait de l'acte faux.",
     card("<b class='gold'>Art. 148</b> : usage de l'acte faux")),
 cue("Les articles 153 et 154 visent aussi le certificat inexact et pour l'obtention d'un document par fausse qualité. Leur numérotation béninoise reste à vérifier.",
     card("<b class='gold'>Art. 153 et 154</b> <span class='red'>numérotation à vérifier</span>")),
 cue("Trois niveaux doivent être distingués : l'irrégularité formelle, la faute professionnelle, civile ou disciplinaire, et le faux intentionnel, pénal.",
     card("<b>1.</b> Irrégularité formelle<br><b>2.</b> Faute professionnelle (civile, disciplinaire)<br><b>3.</b> Faux intentionnel (pénal)")),
 cue("Le faux suppose une altération frauduleuse de la vérité, un écrit protégé et une aptitude à causer un préjudice. L'intention du notaire Félix BALLEY, sa connaissance de la fausseté, doit être établie.",
     card("Éléments : altération frauduleuse · écrit protégé · préjudice possible<br><b class='red'>Intention à établir</b>")),
 cue("La thèse soutenue est que le jugement de 2014 et le communiqué de 2013, antérieurs à l'inscription, établissaient que le décès est survenu le trois décembre deux mille dix. La date du dix juin deux mille seize, portée sur le certificat, est donc fausse.",
     card("Thèse : le jugement (2014) et le communiqué (2013) établissaient le décès au <b class='gold'>3 décembre 2010</b><br>La date du 10 juin 2016 du certificat est <b class='red'>fausse</b>")),
 cue("Il faut enfin distinguer ce que le notaire Félix BALLEY rapporte comme déclaration d'une partie, de ce qu'il affirme avoir lui-même constaté.",
     card("Déclaration d'une partie<br>≠ constatation personnelle de l'officier public")))

scene("Les voies de contrôle et les sanctions prévues par le statut",
 cue("L'article 88 place les études sous la surveillance du procureur général, qui peut tout contrôler. L'article 89 l'autorise à se faire représenter le répertoire et tout document utile.",
     card("<b class='gold'>Art. 88 et 89</b> : surveillance du procureur général ; représentation du répertoire et de tout document utile")),
 cue("L'article 117 prévoit que les infractions à la discipline sont poursuivies par le procureur général, alors même qu'il n'y aurait aucune partie plaignante.",
     pic('art117.jpg','Statut du notariat, article 117'),card("<b class='gold'>Art. 117</b> : poursuite par le procureur général, même sans partie plaignante")),
 cue("L'article 8 donne au bureau de la Chambre nationale des notaires l'examen des réclamations des tiers, y compris contre le notaire Félix BALLEY.",
     card("<b class='gold'>Art. 8</b> : réclamations des tiers examinées par le bureau de la Chambre nationale")),
 cue("Les peines disciplinaires sont le rappel à l'ordre, la censure, la suspension d'un an au plus et la destitution, prononcée par décret en conseil des ministres : articles 112 et 113.",
     card("<b class='gold'>Art. 112-113</b> : rappel à l'ordre · censure · suspension (1 an au plus) · destitution")))

scene("Les limites du dossier et les pièces à obtenir",
 cue("Pour être complet, voici ce qui manque. D'abord la déclaration de mutation par décès elle-même, et l'extrait du répertoire, numéro 1428, page 128, avec la clôture numéro 1492.",
     card("<b class='red'>1.</b> La DMD<br><b class='red'>2.</b> Extrait du répertoire n° 1428, p. 128 (clôture n° 1492, p. 132)")),
 cue("Ensuite, la procuration éventuelle, et le procès-verbal de vérification de l'enregistrement.",
     card("<b class='red'>3.</b> Procuration éventuelle<br><b class='red'>4.</b> PV de vérification de l'enregistrement")),
 cue("Il faut aussi les pages 3/5 et 4/5 du procès-verbal d'audition, et le texte officiel de l'ancien code pénal.",
     card("<b class='red'>5.</b> Pages 3/5 et 4/5 du PV d'audition<br><b class='red'>6.</b> Texte officiel de l'ancien code pénal")),
 cue("Enfin, le décret de nomination du notaire Félix BALLEY. Il déclare résider à Abomey-Calavi, alors que son cachet indique Comé. Le statut impose de résider au lieu fixé : articles 35 et 36.",
     card("<b class='red'>7.</b> Décret de nomination : résidence fixée (art. 35-36)<br><span class='mute'>PV : Abomey-Calavi · cachet : Comé — à vérifier</span>")))

scene("Conclusion",
 cue("Exactitude : la date de décès portée sur le certificat est fausse de cinq ans et demi, et la déclaration a été enregistrée dans le répertoire de l'Étude du notaire Félix BALLEY.",
     card("<b class='gold'>1 · Exactitude</b> : date de décès fausse de 5 ans et demi")),
 cue("Qualité : le notaire Félix BALLEY se prévaut d'une qualité de mandataire qu'aucune pièce n'établit, et qu'il contredit lui-même le 7 septembre 2023.",
     card("<b class='gold'>2 · Qualité</b> : mandataire sans mandat, contredit le 7 septembre 2023")),
 cue("Répertoire : l'inscription intervient plus de trois ans après le communiqué et près de deux ans après le jugement.",
     card("<b class='gold'>3 · Répertoire</b> : inscription postérieure aux pièces qui l'infirment")),
 cue("Transparence : un héritier se voit refuser la délivrance des actes, alors que l'article 82 la permet sans ordonnance.",
     card("<b class='gold'>4 · Transparence</b> : refus opposé à un héritier")),
 cue("Déclarations : devant la Brigade criminelle, le notaire Félix BALLEY avance des justifications successives que les pièces contredisent.",
     card("<b class='gold'>5 · Déclarations</b> : justifications successives, contredites par les pièces")),
 cue("Le notaire Félix BALLEY a juré l'exactitude et la probité. Le certificat et son comportement sont contraires aux textes en vigueur.",
     big("Le notaire Félix BALLEY a juré <span class='gold'>l'exactitude</span> et <span class='gold'>la probité</span>.<br><span class='red'>Le certificat et son comportement sont contraires aux textes en vigueur.</span>")),
 cue("Sensibiliser. Exiger des comptes. L'analyse complète et les pièces sont en ligne : wadagni2026-verite.com",
     big("<span class='gold'>Sensibiliser.</span> Exiger des comptes.<br><span class='gold'>wadagni2026-verite.com</span>")),
 style='background:linear-gradient(135deg,#3b0a0a 0%,#0a1f44 70%)')
